name: Build Tomcat

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out tomcat-users.xml
      uses: actions/checkout@v2

    - name: List project files and java version
      run: |
          ls -ltr
          java -version

    - name: Check out Apache Tomcat
      uses: actions/checkout@v2 # Changed from v4 to v2 revert test
      with:
        repository: apache/tomcat # Repository name with owner
        ref: main               # The branch, tag or SHA to checkout #Change master to main
        path: ./tomcat            # Relative path under $GITHUB_WORKSPACE

    - name: Setup Java 9
      uses: actions/setup-java@v4 # change version from v1 to v4
      with:
        #java-version: '9.0.4'     # The JDK version to make available on the path
        java-version: '21'     # added jmb
        #distribution: 'temurin' # added jmb set to oracle testing temurin extremely fast
        #distribution: 'corretto' # test corretto vs temurin
        distribution: 'temurin' # added jmb winner winner chicken dinner
        #java-package: jdk         # (jre, jdk, or jdk+fx) - defaults to jdk #removed
        #architecture: x64         # (x64 or x86) - defaults to x64 #removed

    - name: List project files and java version
      run: |
          ls -ltr
          java -version

    - name: Copy tomcat-users.xml into Tomcat configuration directory
      run: cp -v tomcat-users.xml ./tomcat/conf/tomcat-users.xml

    - name: Compile Tomcat
      run: |
        cd ./tomcat
        ant
